<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="styletag-530U3C-530U4C-532U3C" ignored="0" tests="4" failures="0" timestamp="23 May 2017 07:56:55 GMT" time="0.035" errors="0">
  <testcase name="@BeforeTest func2" time="0.006" classname="NewTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Assertion failed in my program expected [xyz] but found [abc]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Assertion failed in my program expected [xyz] but found [abc]
	at NewTest.func2(NewTest.java:37)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest func2 -->
  <testcase name="@AfterTest func3" time="0.0" classname="NewTest">
    <skipped/>
  </testcase> <!-- @AfterTest func3 -->
  <testcase name="function1" time="0.0" classname="SecondTest">
    <skipped/>
  </testcase> <!-- function1 -->
  <testcase name="function2" time="0.0" classname="SecondTest">
    <skipped/>
  </testcase> <!-- function2 -->
  <testcase name="fun1" time="0.0" classname="NewTest">
    <skipped/>
  </testcase> <!-- fun1 -->
  <testcase name="justTest" time="0.0" classname="NewTest">
    <skipped/>
  </testcase> <!-- justTest -->
</testsuite>
